# .github/workflows/github-release-publish.yml
name: Publish artifacts to github release

on:
  release:
    types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin,windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "./document-benchmark"
          sha256sum: true
          asset_name: document-benchmark-${{ matrix.goos }}-${{ matrix.goarch }}
          build_command: "make build"
